### ISSUE TITLE
Demo Blog Tags 'not working'

### ISSUE THREAD

**Issue by davidtew** [giansi/gravstrap-theme-skeleton#1]
Tags in the blog http://gravstrap.diblas.net/my-gravtastic-blog (in the demo version) are not directing to the post but to the home page (e.g. a click goes to http://gravstrap.diblas.net/tag:architecture)  .

On the other hand, seems OK on a tag cloud link withing a post page e.g. tag 'architecture' will correctly direct from http://gravstrap.diblas.net/my-gravtastic-blog/daring-fireball-link to http://gravstrap.diblas.net/my-gravtastic-blog/tag:architecture

**Comment by giansi** [comment]
Hi, thank you for reporting. The bug was in the Blog plugin and now it has been fixed: https://github.com/giansi/grav-plugin-blog/commit/7a4974fd7e690c2ae916c59834248a0cf72375ac.
