### ISSUE TITLE
Hamburger menu not opening

### ISSUE THREAD

**Issue by davidtew** [giansi/gravstrap-theme-skeleton#2]
Hello  Giansi - I am not able to open the 'hamburger' navigation (when looking at gravstrap demo from the demo link http://gravstrap.diblas.net/   when in reduced screen size - I  attempted this from within Linux Chrome & Firefox in a narrow browser window

**Comment by giansi** [comment]
I'm fixing it

**Comment by giansi** [comment]
Hi, thank you very much for reporting this bug. I've fixed with the new RC3 release. It should be available at grav web site in a short time, otherwise you can download it from https://github.com/giansi/gravstrap-theme-skeleton/releases.
