### ISSUE TITLE
Can't change menu titles

### ISSUE THREAD

**Issue by axel-rank** [giansi/gravstrap-theme-skeleton#3]
Hi,
installed newest Gravstrap Theme/Skeleton.
If I try to change the menu titles in relevant  .md files nothing happens.
So where/how to change?

**Comment by giansi** [comment]
In order, to define the menu page link, Gravstrap looks for the "menu" property in each page header. When it is not defined, it falls back using the page "title" property.

**Comment by axel-rank** [comment]
Yes I know, and I changed title and menu property in page header and nothing happened/changed ?
Example: user/pages/02.home_single --> home_single_page.md
In page header I change title/menu property --> no result
Metadata changes work.
The same in all subfolders like _clients, _portfolio etc.
Changes of menu/title property in page header do not work.

**Comment by axel-rank** [comment]
I just reinstalled Gravstrap 0.9.13
Everything works as expected again
