### ISSUE TITLE
gravstrap skeleton install error

### ISSUE THREAD

**Issue by msharp1** [giansi/gravstrap-theme-skeleton#4]
Hi,

I have extracted the zip file on my Ubuntu and get the following error when browsing : 

Whoops\Exception\ErrorException thrown with message "Method Grav\Common\Page\Medium\ImageMedium::__toString() must not throw an exception"

Stacktrace:
#0 Whoops\Exception\ErrorException in /srv/web/gravstrap-skeleton/cache/twig/dc/dc99d125cb8f19bb5264d7f7d6ce9852e8979c3e17b6ec065ab3ddf8d1d05ad7.php:0

**Comment by giansi** [comment]
Hi,
it is a permission problem when you use it under a non standard apache document root. You can fix it running these commands under the gravstrap folder:

sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX var
sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX *
sudo setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX *

If you try with the PHP internal webserver it works fine
